In [1]:
import numpy as np


## 1. The elementary transformations needed in Gaussian elimination are:
1. Row Swapping
2. Row Scaling
3. Row Addition


In [2]:
M = [[1,2,3], \
     [4,5,6], \
     [7,8,9]]
M = np.array(M)

In [3]:
def row_swap(M, i, j):
    mat = M.copy()
    mat[i] = M[j]
    mat[j] = M[i]
    return mat

In [4]:
row_swap(M, 0,1)

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [5]:
def row_scale(M, row, scaler):
    M[row] = M[row]*scaler
    return M

In [7]:
row_scale(M, 1, 5)

array([[ 1,  2,  3],
       [20, 25, 30],
       [ 7,  8,  9]])

In [8]:
def row_add(M, i, j, scaler = 1):
    mat = M.copy()
    mat[i] = mat[i]*scaler + mat[j]
    return mat

In [10]:
row_add(M, 1,2, 1)

array([[ 1,  2,  3],
       [27, 33, 39],
       [ 7,  8,  9]])

# Q2.Using the above elementary transformations we can reduce rows to upper triangular
system and then back substitution can be used. Therefore, we have the following two
more tasks:

1. Row Reduction
2. Back Substitution.
3. Forward Substitution

In [20]:
def row_reduction(matrix):
    """
    Perform row reduction (Gaussian elimination) on the given matrix.

    Parameters:
    - matrix: 2D NumPy array representing the matrix
    """
    rows, cols = matrix.shape
    for pivot_row in range(min(rows, cols)):
        # Ensure the pivot element is nonzero
        if matrix[pivot_row, pivot_row] == 0:
            non_zero_row = np.argmax(matrix[pivot_row:, pivot_row]) + pivot_row
            row_swap(matrix, pivot_row, non_zero_row)

        # Make the pivot element 1
        pivot_value = matrix[pivot_row, pivot_row]
        row_scale(matrix, pivot_row, 1 / pivot_value)

        # Eliminate nonzero values below the pivot
        for i in range(pivot_row + 1, rows):
            multiplier = matrix[i, pivot_row]
            row_add(matrix, pivot_row, i, -multiplier)

def forward_substitution(matrix, b):
    """
    Perform forward substitution to solve for variables in a lower triangular system.

    Parameters:
    - matrix: Lower triangular matrix (2D NumPy array)
    - b: 1D NumPy array representing the right-hand side of the system
    """
    n = len(b)
    x = np.zeros(n)
    for i in range(n):
        x[i] = b[i] - np.dot(matrix[i, :i], x[:i])
    return x

def back_substitution(matrix, b):
    """
    Perform back substitution to solve for variables in an upper triangular system.

    Parameters:
    - matrix: Upper triangular matrix (2D NumPy array)
    - b: 1D NumPy array representing the right-hand side of the system
    """
    n = len(b)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(matrix[i, i + 1:], x[i + 1:])) / matrix[i, i]
    return x


## 3.  Finally write the code for the main function
(a) Solve Linear System,and check it for various linear systems.

In [26]:
def solve_linear_system(A, b):
    """
    Solve a linear system Ax = b using Gaussian elimination.

    Parameters:
    - A: Coefficient matrix (2D NumPy array)
    - b: Right-hand side vector (1D NumPy array)

    Returns:
    - x: Solution vector
    """
    # Combine A and b into an augmented matrix
    augmented_matrix = np.column_stack((A, b))

    # Apply row reduction
    row_reduction(augmented_matrix)

    # Separate the augmented matrix back into A and b
    A_reduced = augmented_matrix[:, :-1]
    b_reduced = augmented_matrix[:, -1]

    # Solve the system using back substitution
    y = forward_substitution(A_reduced, b_reduced)
    x = back_substitution(A_reduced, y)

    return x

In [27]:
# Example usage
A1 = np.array([[2, 5, 0, -4, 6],
              [-4, -4, -3, 7, 36],
              [-6, -3, -7, -6, 35],
              [-1, 2, -6, 63, 1]])

b1 = A1[:, -1]  # Right-hand side vector for the first system

solution1 = solve_linear_system(A1[:, :-1], b1)
print("Solution 1:")
print(solution1)

# Example 2
A2 = np.array([[4, -1, 2, 3],
               [0, -2, 7, -4],
               [0, 0, 6, 5],
               [0, 0, 0, 3]])

b2 = np.array([20, -7, 4, 6])

solution2 = solve_linear_system(A2, b2)
print("\nSolution 2:")
print(solution2)


Solution 1:
[ 27. -12.  -5.   0.]

Solution 2:
[ 5. -1.  0.  2.]


## 4. Obtain the solution for the following system of equations using the code written by you.

$\begin{aligned} 2 x_1+5 x_2+0 x_3-4 x_4= & 6 \\ -4 x_1-4 x_2-3 x_3+7 x_4= & 36 \\ -6 x_1-3 x_2-7 x_3-6 x_4= & 35 \\ -x_1+2 x_2-6 x_3+5 x_4= & 63\end{aligned}$

In [36]:
A = np.array([[2, 5, 0, -4, 6],
              [-4, -4, -3, 7, 36],
              [-6, -3, -7, -6, 35],
              [-1, 2, -6, 5, 63]])
A

array([[ 2,  5,  0, -4,  6],
       [-4, -4, -3,  7, 36],
       [-6, -3, -7, -6, 35],
       [-1,  2, -6,  5, 63]])

In [41]:
b = A[:,-1]
A = A[:,:-1]
# Solve the system
solution = solve_linear_system(A, b)

print("Solution:")
print(solution)


Solution:
[27. -5. -5.  7.]
